##docker-compose 파일
name: <Zabbix Monitoring>
services:
    mysql:
        volumes:
            - mysql-volume:/var/lib/mysql
        container_name: mysql-server
        tty: true
        environment:
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=
            - MYSQL_PASSWORD=
            - MYSQL_ROOT_PASSWORD=
        networks:
            - zabbix-net
        restart: unless-stopped
        image: mysql:8.0
        command: --character-set-server=utf8 --collation-server=utf8_bin
    zabbix-java-gateway:
        container_name: zabbix-java-gateway
        tty: true
        networks:
            - zabbix-net
        restart: unless-stopped
        image: zabbix/zabbix-java-gateway
    zabbix-server-mysql:
        container_name: zabbix-server-mysql
        tty: true
        environment:
            - DB_SERVER_HOST=mysql-server
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=
            - MYSQL_PASSWORD=
            - MYSQL_ROOT_PASSWORD=
            - ZBX_JAVAGATEWAY=zabbix-java-gateway
        links:
            - mysql-server:mysql
            - zabbix-java-gateway:zabbix-java-gateway
        ports:
            - 10051:10051
        networks:
            - zabbix-net
        restart: unless-stopped
        image: zabbix/zabbix-server-mysql
    zabbix-web-nginx-mysql:
        container_name: zabbix-web-nginx-mysql
        tty: true
        environment:
            - DB_SERVER_HOST=mysql-server
            - MYSQL_DATABASE=zabbix
            - MYSQL_USER=
            - MYSQL_PASSWORD=
            - MYSQL_ROOT_PASSWORD=
        links:
            - mysql-server:mysql
            - zabbix-server-mysql:zabbix-server
        ports:
            - 80:8080
        networks:
            - zabbix-net
        restart: unless-stopped
        image: zabbix/zabbix-web-nginx-mysql
    zabbix-agent2:
        container_name: zabbix-agent2
        links:
            - mysql-server:mysql
            - zabbix-server-mysql:zabbix-server
        environment:
            - ZBX_HOSTNAME=Zabbix server
            - ZBX_SERVER_HOST=Zabbix Server Container IP
        networks:
            - zabbix-net
        image: zabbix/zabbix-agent2
networks:
    zabbix-net:
        external: true
        name: zabbix-net
volumes:
    mysql-volume:
        external: true
        name: mysql-volume

프록시
name: <your project name>
services:
    mysql:
        volumes:
            - proxy-volume:/var/lib/mysql
        container_name: mysql-server
        tty: true
        environment:
            - MYSQL_DATABASE=zabbix_proxy
            - MYSQL_USER=
            - MYSQL_PASSWORD=
            - MYSQL_ROOT_PASSWORD=
        networks:
            - zabbix-net
        restart: unless-stopped
        image: mysql:8.0
        command: --character-set-server=utf8 --collation-server=utf8_bin
    zabbix-proxy-mysql:
        container_name: zabbix-proxy-mysql
        environment:
            - DB_SERVER_HOST=mysql-server
            - MYSQL_USER=
            - MYSQL_PASSWORD=
            - ZBX_HOSTNAME=zabbixProxy
            - ZBX_SERVER_HOST= zabbixserverIP
        networks:
            - zabbix-net
        init: true
        image: zabbix/zabbix-proxy-mysql
networks:
    zabbix-net:
        external: true
        name: zabbix-net
volumes:
    proxy-volume:
        external: true
        name: proxy-volume
